export const events = [
  { name: "JAL", category: "simple" },
  { name: "SAGAI", category: "simple" },
  { name: "KANKU PAGLA", category: "medium" },
  { name: "LAGAN LAKHVA", category: "medium" },
  { name: "LAGAN VADHAVA", category: "medium" },
  { name: "VANA RASAM", category: "medium" },
  { name: "MEHENDI", category: "medium" },
  { name: "HALDI", category: "medium" },
  { name: "MANDAP", category: "medium" },
  { name: "POOL PARTY", category: "medium" },
  { name: "RASS GARBA", category: "complex" },
  { name: "DJ NIGHT", category: "complex" },
  { name: "MUSICAL NIGHT", category: "complex" },
  { name: "SUFI NIGHT", category: "complex" },
  { name: "WEDDING", category: "complex" },
  { name: "RECEPTION", category: "complex" },
  { name: "2 EVENTS", category: "twofunction" },
  { name: "3 EVENTS", category: "threefunction" },
];

export const services = {
  simple: [
    { name: "Candid photographer", price: 15000 },
    { name: "Ceremony Photographer", price: 12000 },
    { name: "Traditional videographer", price: 12000 },
    { name: "Cinematographer", price: 30000 },
    { name: "Family photographer", price: 12000 },
  ],
  medium: [
    { name: "Candid photographer", price: 18000 },
    { name: "InHouse Photographer", price: 8000 },
    { name: "Ceremony Photographer", price: 15000 },
    { name: "Traditional videographer", price: 15000 },
    { name: "InHouse Videographer", price: 10000 },
    { name: "Cinematographer", price: 35000 },
    { name: "InHouse Cinematographer", price: 12000 },
    { name: "Family photographer", price: 12000 },
  ],
  complex: [
    { name: "Candid photographer", price: 22000 },
    { name: "InHouse Photographer", price: 10000 },
    { name: "Ceremony Photographer", price: 18000 },
    { name: "Traditional videographer", price: 18000 },
    { name: "InHouse Videographer", price: 12000 },
    { name: "Cinematographer", price: 40000 },
    { name: "InHouse Cinematographer", price: 15000 },
    { name: "Family photographer", price: 15000 },
    { name: "Drone", price: 15000 },
    { name: "Live", price: 60000 },
    { name: "LED 8x12", price: 12000 },
    { name: "LED 10x18", price: 24000 },
    { name: "SameDayEdit", price: 25000 },
    { name: "Youtube Live", price: 15000 },
    { name: "AI Scanner", price: 5000 },
  ],
  twofunction: [
    { name: "Candid photographer", price: 30000 },
    { name: "Ceremony Photographer", price: 22000 },
    { name: "Traditional videographer", price: 24000 },
    { name: "Cinematographer", price: 45000 },
    { name: "Drone", price: 20000 },
  ],
  threefunction: [
    { name: "Candid photographer", price: 38000 },
    { name: "Ceremony Photographer", price: 29000 },
    { name: "Traditional videographer", price: 30000 },
    { name: "Cinematographer", price: 45000 },
    { name: "Drone", price: 20000 },
  ],
};

export const extras = [
  { name: "Reel", price: 3000 },
  { name: "Wedding film", price: 15000 },
  { name: "2 TB harddisk", price: 7000 },
  { name: "4 TB hardisk", price: 14000 },
  { name: "Per Day Edit", price: 12000 },
];
